-- Endless Space: the whole database in one file. GENERATED by `npm run db:setup`
-- from supabase/migrations/*.sql: edit those, not this.
--
-- Safe on a fresh project. If pasting this into the Supabase SQL editor gets cut off,
-- use the small files in supabase/parts/ instead, one at a time, in order.

-- ===== 0001_init.sql =====

-- Endless Space: players, cloud saves, cores, ranked runs and the weekly board.
-- Run with `supabase db push` (or paste into the SQL editor). Turn on
-- anonymous sign-ins under Authentication > Providers.

-- A short public name for the leaderboard ("pilot-3fa2" until there are names).
create table if not exists public.players (
  user_id uuid primary key references auth.users on delete cascade,
  name text not null default ('pilot-' || substr(md5(random()::text), 1, 4)),
  created_at timestamptz not null default now()
);

-- Cloud save: every saved key as JSON, and when the device wrote it (ms).
create table if not exists public.saves (
  user_id uuid primary key references auth.users on delete cascade,
  data jsonb not null,
  saved_at bigint not null
);

-- Cores live here. Players can read their balance; only the functions below
-- (and the store webhook, with the service key) change it.
create table if not exists public.wallets (
  user_id uuid primary key references auth.users on delete cascade,
  cores integer not null default 0 check (cores >= 0),
  earned_today integer not null default 0,
  earned_day date not null default current_date
);

create table if not exists public.core_log (
  id bigserial primary key,
  user_id uuid not null references auth.users on delete cascade,
  delta integer not null,
  reason text not null,
  at timestamptz not null default now()
);

-- Ranked runs, written by the submit-run function after its checks.
create table if not exists public.runs (
  id bigserial primary key,
  user_id uuid not null references auth.users on delete cascade,
  week date not null,
  league smallint not null,
  score integer not null,
  seconds real not null,
  distance real not null,
  finished boolean not null,
  path real[] not null,
  at timestamptz not null default now()
);
create index if not exists runs_board on public.runs (week, league, score desc);

-- Each player's best run per week and league.
create or replace view public.board with (security_invoker = false) as
  select distinct on (r.week, r.league, r.user_id)
    r.week, r.league, r.user_id, coalesce(p.name, 'pilot') as name, r.score
  from public.runs r
  left join public.players p on p.user_id = r.user_id
  order by r.week, r.league, r.user_id, r.score desc;

alter table public.players enable row level security;
alter table public.saves enable row level security;
alter table public.wallets enable row level security;
alter table public.core_log enable row level security;
alter table public.runs enable row level security;

drop policy if exists "own player" on public.players;
create policy "own player" on public.players for select using (auth.uid() = user_id);
drop policy if exists "own save read" on public.saves;
create policy "own save read" on public.saves for select using (auth.uid() = user_id);
drop policy if exists "own save write" on public.saves;
create policy "own save write" on public.saves for insert with check (auth.uid() = user_id);
drop policy if exists "own save update" on public.saves;
create policy "own save update" on public.saves for update using (auth.uid() = user_id);
drop policy if exists "own wallet" on public.wallets;
create policy "own wallet" on public.wallets for select using (auth.uid() = user_id);
grant select on public.board to anon, authenticated;

-- New accounts get a player row and an empty wallet.
create or replace function public.on_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.players (user_id) values (new.id) on conflict do nothing;
  insert into public.wallets (user_id) values (new.id) on conflict do nothing;
  return new;
end $$;

create or replace trigger on_auth_user_created after insert on auth.users
  for each row execute function public.on_new_user();

-- Cores earned in play (login calendar, quests, the pass): capped per day, so
-- an edited client can't print them.
create or replace function public.earn_cores(amount integer, reason text) returns integer
language plpgsql security definer set search_path = public as $$
declare
  cap constant integer := 120;
  w public.wallets;
  give integer;
begin
  select * into w from public.wallets where user_id = auth.uid() for update;
  if not found then return 0; end if;
  if w.earned_day <> current_date then
    w.earned_today := 0;
  end if;
  give := greatest(0, least(amount, cap - w.earned_today));
  update public.wallets
    set cores = cores + give, earned_today = w.earned_today + give, earned_day = current_date
    where user_id = auth.uid();
  if give > 0 then
    insert into public.core_log (user_id, delta, reason) values (auth.uid(), give, reason);
  end if;
  return give;
end $$;

create or replace function public.spend_cores(amount integer, reason text) returns boolean
language plpgsql security definer set search_path = public as $$
begin
  if amount <= 0 then return false; end if;
  update public.wallets set cores = cores - amount where user_id = auth.uid() and cores >= amount;
  if not found then return false; end if;
  insert into public.core_log (user_id, delta, reason) values (auth.uid(), -amount, reason);
  return true;
end $$;

-- Purchases (the store webhook calls this with the service key).
create or replace function public.grant_cores(player uuid, amount integer, reason text) returns void
language plpgsql security definer set search_path = public as $$
begin
  insert into public.wallets (user_id, cores) values (player, amount)
    on conflict (user_id) do update set cores = public.wallets.cores + amount;
  insert into public.core_log (user_id, delta, reason) values (player, amount, reason);
end $$;

revoke execute on function public.grant_cores from anon, authenticated;
grant execute on function public.earn_cores, public.spend_cores to authenticated;

-- ===== 0002_store.sql =====

-- Store purchases from RevenueCat's webhook. Each event is kept once (by its
-- id), so a retried webhook never pays twice.

create table if not exists public.store_events (
  id text primary key,
  user_id uuid references auth.users on delete set null,
  product text not null,
  type text not null,
  at timestamptz not null default now()
);

alter table public.store_events enable row level security;
drop policy if exists "own purchases" on public.store_events;
create policy "own purchases" on public.store_events for select using (auth.uid() = user_id);

-- ===== 0003_leaderboards.sql =====

-- Leaderboards: one table of each player's best per board, filled by submit_run
-- (which checks a run is possible) and read through leaderboard().
--
-- Boards:
--   ranked          the week's run, one board per week and league
--   endless         every area in turn, all time
--   solo:<env>      one environment endlessly, all time (open-ground, canyon,
--                   ship, ice, asteroids, volcanic)
--
-- Everything is plain SQL: there is no function to deploy.

-- Pilot names: shown on the boards. hidden takes a player off them.
alter table public.players add column if not exists hidden boolean not null default false;
alter table public.players add column if not exists name_changed_at timestamptz;

-- Every submitted run, kept for checking and clean-up. Written only by submit_run.
alter table public.runs add column if not exists board text not null default 'ranked';
create index if not exists runs_by_user on public.runs (user_id, at desc);

-- The best run per player on each board (period is the week's Monday for
-- ranked, 'all' for the rest; league is 0 outside ranked).
create table if not exists public.bests (
  board text not null,
  period text not null,
  league smallint not null default 0,
  user_id uuid not null references auth.users on delete cascade,
  score integer not null,
  seconds real not null,
  achieved_at timestamptz not null default now(),
  primary key (board, period, league, user_id)
);
create index if not exists bests_top on public.bests (board, period, league, score desc, achieved_at);

alter table public.bests enable row level security; -- no policies: read through leaderboard()

-- Carry over what the old board view showed.
insert into public.bests (board, period, league, user_id, score, seconds, achieved_at)
select distinct on (week, league, user_id) 'ranked', week::text, league, user_id, score, seconds, at
from public.runs
order by week, league, user_id, score desc, at
on conflict do nothing;

drop view if exists public.board;

-- The checks on a run: is it possible? (not that it's honest: a full re-fly on the
-- server is the next step, see docs/leaderboards.md). Raises a reason if not.
create or replace function public.check_run(
  p_board text,
  p_league smallint,
  p_score integer,
  p_seconds real,
  p_distance real,
  p_path real[]
) returns void
language plpgsql immutable as $$
declare
  -- Keep these in step with CONFIG (tests/sql.test.ts checks).
  c_points_per_unit constant numeric := 0.85;  -- CONFIG.score.pointsPerUnit
  c_bonus_share constant numeric := 1.5;       -- pickups, near-miss chains and boost on top of distance (generous)
  c_top_speed constant numeric := 115;         -- units/s: CONFIG.speed.max with full boost, plus a margin
  c_path_step constant integer := 4;           -- units of distance per path sample
  c_max_sideways constant numeric := 12;       -- sideways travel per path sample, at most
begin
  if p_board !~ '^(ranked|endless|solo:(open-ground|canyon|ship|ice|asteroids|volcanic))$' then
    raise exception 'unknown board' using errcode = '22023';
  end if;
  if p_score is null or p_seconds is null or p_distance is null or p_score < 0 or p_score > 50000000 then
    raise exception 'bad score' using errcode = '22023';
  end if;
  if p_seconds < 5 or p_seconds > 21600 or p_distance <= 0 then
    raise exception 'bad time or distance' using errcode = '22023';
  end if;
  if p_score > p_distance * c_points_per_unit * (1 + c_bonus_share) + 500 then
    raise exception 'score too high for the distance' using errcode = '22023';
  end if;
  if p_distance / greatest(0.1, p_seconds) > c_top_speed then
    raise exception 'too fast' using errcode = '22023';
  end if;
  if p_board = 'ranked' then
    if p_league is null or p_league < 0 or p_league > 6 then
      raise exception 'bad league' using errcode = '22023';
    end if;
    -- Ranked runs carry the ship's path (the ghost), one sample every few units.
    if abs(coalesce(array_length(p_path, 1), 0) - ceil(p_distance / c_path_step)) > 2 then
      raise exception 'path does not match the distance' using errcode = '22023';
    end if;
    if exists (
      select 1 from generate_subscripts(p_path, 1) i
      where i > 1 and abs(p_path[i] - p_path[i - 1]) > c_max_sideways
    ) then
      raise exception 'path jumps' using errcode = '22023';
    end if;
  end if;
end $$;

-- Submit a finished run: checks it, keeps it if it is a best, and says where it ranks.
create or replace function public.submit_run(
  p_board text,
  p_league smallint,
  p_score integer,
  p_seconds real,
  p_distance real,
  p_finished boolean,
  p_path real[] default '{}'
) returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  c_min_gap constant interval := interval '8 seconds'; -- between submissions from one player
  c_max_per_day constant integer := 400;
  me uuid := auth.uid();
  week_start date := (date_trunc('week', now() at time zone 'utc'))::date;
  per text;
  lg smallint;
  last_at timestamptz;
  today integer;
  old_best integer;
  now_rank integer;
begin
  if me is null then raise exception 'sign in first' using errcode = '28000'; end if;
  perform public.check_run(p_board, p_league, p_score, p_seconds, p_distance, p_path);
  if p_board = 'ranked' then
    per := week_start::text;
    lg := p_league;
  else
    per := 'all';
    lg := 0;
  end if;

  -- Rate limits: a run takes at least a few seconds, so faster is a script.
  select max(at), count(*) filter (where at > now() - interval '1 day') into last_at, today
  from public.runs where user_id = me;
  if last_at is not null and now() - last_at < c_min_gap then
    raise exception 'too many runs too quickly' using errcode = '22023';
  end if;
  if today >= c_max_per_day then
    raise exception 'too many runs today' using errcode = '22023';
  end if;

  insert into public.runs (user_id, week, league, score, seconds, distance, finished, path, board)
  values (me, week_start, lg, p_score, p_seconds, p_distance, p_finished, coalesce(p_path, '{}'), p_board);

  select score into old_best from public.bests
  where board = p_board and period = per and league = lg and user_id = me;
  if old_best is null or p_score > old_best then
    insert into public.bests (board, period, league, user_id, score, seconds)
    values (p_board, per, lg, me, p_score, p_seconds)
    on conflict (board, period, league, user_id)
    do update set score = excluded.score, seconds = excluded.seconds, achieved_at = now();
  end if;

  select 1 + count(*) into now_rank
  from public.bests b join public.players pl on pl.user_id = b.user_id and not pl.hidden
  where b.board = p_board and b.period = per and b.league = lg
    and b.score > greatest(p_score, coalesce(old_best, 0));

  return jsonb_build_object(
    'rank', now_rank,
    'best', greatest(p_score, coalesce(old_best, 0)),
    'newBest', old_best is null or p_score > old_best
  );
end $$;

-- A board, best first: the top p_limit pilots and, if you are further down,
-- your own row at the end with your rank.
drop function if exists public.leaderboard(text, text, smallint, integer); -- its columns change in 0004
create function public.leaderboard(
  p_board text,
  p_period text default 'all',
  p_league smallint default 0,
  p_limit integer default 50
) returns table (rank bigint, name text, score integer, you boolean)
language plpgsql stable security definer set search_path = public as $$
#variable_conflict use_column
declare
  me uuid := auth.uid();
  n integer := least(greatest(coalesce(p_limit, 50), 1), 100);
  mine public.bests;
  my_rank bigint;
begin
  return query
    select (row_number() over (order by t.score desc, t.achieved_at, t.user_id))::bigint,
           t.name, t.score, t.user_id = me
    from (
      select b.user_id, b.score, b.achieved_at, pl.name
      from public.bests b join public.players pl on pl.user_id = b.user_id and not pl.hidden
      where b.board = p_board and b.period = p_period and b.league = p_league
      order by b.score desc, b.achieved_at, b.user_id
      limit n
    ) t
    order by 1;

  select * into mine from public.bests b
  where b.board = p_board and b.period = p_period and b.league = p_league and b.user_id = me;
  if found then
    select 1 + count(*) into my_rank
    from public.bests b join public.players pl on pl.user_id = b.user_id and not pl.hidden
    where b.board = p_board and b.period = p_period and b.league = p_league
      and (b.score > mine.score
        or (b.score = mine.score and (b.achieved_at < mine.achieved_at
          or (b.achieved_at = mine.achieved_at and b.user_id < me))));
    if my_rank > n then
      return query select my_rank, (select pl.name from public.players pl where pl.user_id = me), mine.score, true;
    end if;
  end if;
end $$;

-- Change your pilot name: 3 to 16 letters, numbers, spaces, - or _; not taken;
-- once an hour at most.
create or replace function public.set_pilot_name(p_name text) returns text
language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  clean text := btrim(coalesce(p_name, ''));
  changed timestamptz;
begin
  if me is null then raise exception 'sign in first' using errcode = '28000'; end if;
  if clean !~ '^[A-Za-z0-9_ -]{3,16}$' then
    raise exception 'use 3 to 16 letters, numbers, spaces, - or _' using errcode = '22023';
  end if;
  if exists (select 1 from public.players where lower(name) = lower(clean) and user_id <> me) then
    raise exception 'that name is taken' using errcode = '22023';
  end if;
  select name_changed_at into changed from public.players where user_id = me;
  if changed is not null and now() - changed < interval '1 hour' then
    raise exception 'you can change your name once an hour' using errcode = '22023';
  end if;
  update public.players set name = clean, name_changed_at = now() where user_id = me;
  return clean;
end $$;

revoke execute on function public.check_run from public, anon, authenticated; -- only submit_run calls it
revoke execute on function public.submit_run, public.leaderboard, public.set_pilot_name from public, anon;
grant execute on function public.submit_run, public.leaderboard, public.set_pilot_name to authenticated;

-- ===== 0004_premium.sql =====

-- Premium: the one-off purchase that removes ads and gives premium looks. The
-- purchase webhook already keeps every purchase in store_events, so owning
-- premium is a row there; a player reads their own (see the "own purchases"
-- policy), and the boards show a badge for it.

create index if not exists store_events_by_user on public.store_events (user_id, product);

-- leaderboard() gains a premium column, so it's made again (a function's
-- columns can't change in place).
drop function if exists public.leaderboard(text, text, smallint, integer);

-- A board, best first: the top p_limit pilots and, if you are further down,
-- your own row at the end with your rank.
create function public.leaderboard(
  p_board text,
  p_period text default 'all',
  p_league smallint default 0,
  p_limit integer default 50
) returns table (rank bigint, name text, score integer, you boolean, premium boolean)
language plpgsql stable security definer set search_path = public as $$
#variable_conflict use_column
declare
  me uuid := auth.uid();
  n integer := least(greatest(coalesce(p_limit, 50), 1), 100);
  mine public.bests;
  my_rank bigint;
begin
  return query
    select (row_number() over (order by t.score desc, t.achieved_at, t.user_id))::bigint,
           t.name, t.score, t.user_id = me, t.premium
    from (
      select b.user_id, b.score, b.achieved_at, pl.name,
             exists (select 1 from public.store_events e where e.user_id = b.user_id and e.product = 'premium') as premium
      from public.bests b join public.players pl on pl.user_id = b.user_id and not pl.hidden
      where b.board = p_board and b.period = p_period and b.league = p_league
      order by b.score desc, b.achieved_at, b.user_id
      limit n
    ) t
    order by 1;

  select * into mine from public.bests b
  where b.board = p_board and b.period = p_period and b.league = p_league and b.user_id = me;
  if found then
    select 1 + count(*) into my_rank
    from public.bests b join public.players pl on pl.user_id = b.user_id and not pl.hidden
    where b.board = p_board and b.period = p_period and b.league = p_league
      and (b.score > mine.score
        or (b.score = mine.score and (b.achieved_at < mine.achieved_at
          or (b.achieved_at = mine.achieved_at and b.user_id < me))));
    if my_rank > n then
      return query select my_rank, (select pl.name from public.players pl where pl.user_id = me), mine.score, true,
        exists (select 1 from public.store_events e where e.user_id = me and e.product = 'premium');
    end if;
  end if;
end $$;

revoke execute on function public.leaderboard from public, anon;
grant execute on function public.leaderboard to authenticated;

-- ===== 0005_delete_account.sql =====

-- Delete your own account from the game (both stores ask for this). The
-- account goes, and with it (on delete cascade) the player, save, wallet,
-- cores log, runs and bests. Purchase records stay, without the account,
-- for the books (store_events.user_id is set to null).

create or replace function public.delete_my_account() returns void
language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null then
    raise exception 'not signed in';
  end if;
  delete from auth.users where id = auth.uid();
end;
$$;

revoke execute on function public.delete_my_account from public, anon;
grant execute on function public.delete_my_account to authenticated;

-- ===== 0006_ship_looks.sql =====

-- Ships on the boards: each player's equipped looks (hull, paint, markings,
-- fins, decal, engine colour, trail, and the rank and league their badge
-- decals show), so the leaderboard can draw everyone's ship next to their name.

alter table public.players add column if not exists ship jsonb;

-- Set your own. Only the shape is checked (known slots, short ids, small
-- numbers): which looks a player owns lives on their device.
create or replace function public.set_ship(p_ship jsonb) returns void
language plpgsql security definer set search_path = public as $$
declare
  k text;
  v jsonb;
begin
  if auth.uid() is null then
    raise exception 'not signed in';
  end if;
  if jsonb_typeof(p_ship) <> 'object' or octet_length(p_ship::text) > 400 then
    raise exception 'not a ship' using errcode = '22023';
  end if;
  for k, v in select * from jsonb_each(p_ship) loop
    if k in ('hull', 'paint', 'markings', 'fins', 'decal', 'engine', 'trail') then
      if jsonb_typeof(v) <> 'string' or (v #>> '{}') !~ '^[a-z0-9-]{1,24}$' then
        raise exception 'not a look: %', k using errcode = '22023';
      end if;
    elsif k in ('rank', 'league', 'division') then
      if jsonb_typeof(v) <> 'number' or (v #>> '{}')::numeric not between 0 and 99 then
        raise exception 'not a number: %', k using errcode = '22023';
      end if;
    else
      raise exception 'not a slot: %', k using errcode = '22023';
    end if;
  end loop;
  update public.players set ship = p_ship where user_id = auth.uid();
end;
$$;

revoke execute on function public.set_ship from public, anon;
grant execute on function public.set_ship to authenticated;

-- leaderboard() gains a ship column, so it's made again (a function's
-- columns can't change in place).
drop function if exists public.leaderboard(text, text, smallint, integer);

-- A board, best first: the top p_limit pilots and, if you are further down,
-- your own row at the end with your rank.
create function public.leaderboard(
  p_board text,
  p_period text default 'all',
  p_league smallint default 0,
  p_limit integer default 50
) returns table (rank bigint, name text, score integer, you boolean, premium boolean, ship jsonb)
language plpgsql stable security definer set search_path = public as $$
#variable_conflict use_column
declare
  me uuid := auth.uid();
  n integer := least(greatest(coalesce(p_limit, 50), 1), 100);
  mine public.bests;
  my_rank bigint;
begin
  return query
    select (row_number() over (order by t.score desc, t.achieved_at, t.user_id))::bigint,
           t.name, t.score, t.user_id = me, t.premium, t.ship
    from (
      select b.user_id, b.score, b.achieved_at, pl.name, pl.ship,
             exists (select 1 from public.store_events e where e.user_id = b.user_id and e.product = 'premium') as premium
      from public.bests b join public.players pl on pl.user_id = b.user_id and not pl.hidden
      where b.board = p_board and b.period = p_period and b.league = p_league
      order by b.score desc, b.achieved_at, b.user_id
      limit n
    ) t
    order by 1;

  select * into mine from public.bests b
  where b.board = p_board and b.period = p_period and b.league = p_league and b.user_id = me;
  if found then
    select 1 + count(*) into my_rank
    from public.bests b join public.players pl on pl.user_id = b.user_id and not pl.hidden
    where b.board = p_board and b.period = p_period and b.league = p_league
      and (b.score > mine.score
        or (b.score = mine.score and (b.achieved_at < mine.achieved_at
          or (b.achieved_at = mine.achieved_at and b.user_id < me))));
    if my_rank > n then
      return query select my_rank, pl.name, mine.score, true,
        exists (select 1 from public.store_events e where e.user_id = me and e.product = 'premium'), pl.ship
        from public.players pl where pl.user_id = me;
    end if;
  end if;
end $$;

revoke execute on function public.leaderboard from public, anon;
grant execute on function public.leaderboard to authenticated;

-- ===== 0007_wallet_credits.sql =====

-- Credits on the server too, next to cores, so a balance can be changed from
-- the dashboard (Table Editor > wallets > credits). Credits are still earned
-- and spent on the device; sync_credits merges the two: whatever changed on
-- the server since the device last synced is added to the device's balance.

alter table public.wallets add column if not exists credits bigint check (credits >= 0);

-- p_credits: the device's balance now. p_last: what the server said last time
-- (null if this device has never synced). Returns the balance to keep.
create or replace function public.sync_credits(p_credits bigint, p_last bigint) returns bigint
language plpgsql security definer set search_path = public as $$
declare
  have bigint;
  keep bigint;
begin
  if auth.uid() is null then
    raise exception 'not signed in';
  end if;
  if p_credits is null or p_credits < 0 or p_credits > 1000000000 then
    raise exception 'not a balance' using errcode = '22023';
  end if;
  select credits into have from public.wallets where user_id = auth.uid() for update;
  if not found then
    return p_credits;
  end if;
  if have is null then
    keep := p_credits; -- the first sync: the device's balance
  elsif p_last is null then
    keep := have; -- a device that has never synced: the server's
  else
    keep := greatest(0, p_credits + (have - p_last)); -- the device's, plus any change made on the server
  end if;
  update public.wallets set credits = keep where user_id = auth.uid();
  return keep;
end;
$$;

revoke execute on function public.sync_credits from public, anon;
grant execute on function public.sync_credits to authenticated;

-- ===== 0008_max_out.sql =====

-- Max out a player from the SQL editor (for testing):
--   update public.players set max_out = true where name = 'Ace Pilot';
-- The next time they open the game (or come back to it) it gives them the top
-- rank and league, every look, every upgrade at its top tier, every level and
-- 100,000 credits, then clears the flag. Set it again to do it again.

alter table public.players add column if not exists max_out boolean not null default false;

-- Take the flag (true once, then it's cleared).
create or replace function public.take_max_out() returns boolean
language plpgsql security definer set search_path = public as $$
declare
  was boolean;
begin
  update public.players set max_out = false
  where user_id = auth.uid() and max_out
  returning true into was;
  return coalesce(was, false);
end;
$$;

revoke execute on function public.take_max_out from public, anon;
grant execute on function public.take_max_out to authenticated;

-- ===== 0009_name_filter.sql =====

-- No profanity in pilot names. The words are from
-- https://github.com/zautumnz/profane-words (WTFPL), made by
-- `npm run names:build` (scripts/name-filter/). The rules match
-- src/nameFilter.ts, which checks the same in the game first:
--   a name is split into words (at spaces, - and _, and between a small and a
--   capital letter), each read with leetspeak undone and with digits dropped;
--   it's refused if a word, or the whole name run together, is on the list, or
--   if it contains a strong root anywhere.
-- To find names picked before this:  select name from players where name_blocked(name);

create table if not exists public.name_words (
  word text primary key,
  strong boolean not null default false -- refused anywhere in a name, not just as a word
);
alter table public.name_words enable row level security; -- only the functions below read it
revoke all on public.name_words from anon, authenticated;

insert into public.name_words (word, strong) values ('fuck', true), ('fuk', true), ('shit', true), ('cunt', true), ('nigg', true), ('fagg', true), ('faggot', true), ('whore', true), ('slut', true), ('bitch', true), ('penis', true), ('pussy', true), ('porn', true), ('jizz', true), ('twat', true), ('wank', true), ('dildo', true), ('boob', true), ('kike', true), ('chink', true), ('retard', true), ('nazi', true), ('hitler', true), ('sperm', true), ('vagina', true), ('clit', true), ('hentai', true), ('rapist', true), ('molest', true), ('asshole', true), ('bastard', true), ('bollock', true), ('cocksuck', true), ('motherf', true), ('blowjob', true), ('handjob', true), ('skank', true)
on conflict (word) do update set strong = true;

-- BEGIN WORDS
insert into public.name_words (word) values ('abbo'), ('abeed'), ('abuse'), ('acrotomophilia'), ('africoon'), ('ahole'), ('alabamahotpocket'), ('alaskanpipeline'), ('alligatorbait'), ('amcik'), ('anal'), ('analannie'), ('analprobe'), ('analsex'), ('andskota'), ('anilingus'), ('anus'), ('apeshit'), ('arabush'), ('arabushs'), ('areola'), ('areole'), ('argie'), ('arrse'), ('arschloch'), ('arse'), ('arsehole'), ('aryan'), ('ashole'), ('asholes'), ('ass'), ('assbag'), ('assbagger'), ('assbandit'), ('assbang'), ('assbanged'), ('assbanger'), ('assbangs'), ('assbite'), ('assblaster'), ('assclown'), ('asscock'), ('asscowboy'), ('asscracker'), ('asses'), ('assface'), ('assfuck'), ('assfucker'), ('assfukka'), ('assgoblin'), ('asshat'), ('asshead'), ('asshoie'), ('asshole'), ('assholes'), ('assholez'), ('assholz'), ('asshopper'), ('asshore'), ('assjacker'), ('assjockey'), ('asskiss'), ('asskisser'), ('assklown'), ('asslick'), ('asslicker'), ('asslover'), ('assman'), ('assmaster'), ('assmonkey'), ('assmunch'), ('assmuncher'), ('assnigger'), ('asspacker'), ('asspirate'), ('asspuppies'), ('assrammer'), ('assranger'), ('assshit'), ('assshole'), ('asssucker'), ('asswad'), ('asswhole'), ('asswhore'), ('asswipe'), ('asswipes'), ('autoerotic'), ('ayir'), ('azazel'), ('azz'), ('azzhole'), ('babeland'), ('babes'), ('babybatter'), ('babyjuice'), ('backdoorman'), ('badfuck'), ('ballbag'), ('ballgag'), ('ballgravy'), ('ballkicking'), ('balllicker'), ('balllicking'), ('ballsack'), ('ballsucking'), ('bampot'), ('bangbro'), ('bangbros'), ('bangbus'), ('bareback'), ('barelylegal'), ('barenaked'), ('barface'), ('barfface'), ('bassterd'), ('bassterds'), ('bastard'), ('bastardo'), ('bastards'), ('bastardz') on conflict do nothing;
insert into public.name_words (word) values ('basterds'), ('basterdz'), ('bastinado'), ('bazongas'), ('bazooms'), ('bbw'), ('bdsm'), ('beaner'), ('beaners'), ('beaney'), ('beaneys'), ('beardedclam'), ('beastality'), ('beastial'), ('beastiality'), ('beastility'), ('beatch'), ('beatoff'), ('beatyourmeat'), ('beavercleaver'), ('beaverlips'), ('beefcurtains'), ('beeyotch'), ('bellend'), ('beotch'), ('bestial'), ('bestiality'), ('biatch'), ('bicurious'), ('bigass'), ('bigbastard'), ('bigblack'), ('bigbreasts'), ('bigbutt'), ('bigknockers'), ('bigtits'), ('bimbo'), ('bimbos'), ('bint'), ('birdlock'), ('bitch'), ('bitchass'), ('bitched'), ('bitcher'), ('bitchers'), ('bitches'), ('bitchez'), ('bitchin'), ('bitching'), ('bitchslap'), ('bitchtit'), ('bitchy'), ('biteme'), ('bitties'), ('blackcock'), ('blackman'), ('blondeaction'), ('blondeonblonde'), ('blondeonblondeaction'), ('bloodclaat'), ('blowj'), ('blowjob'), ('blowjobs'), ('blowyourl'), ('blowyourload'), ('bluegum'), ('bluegums'), ('bluewaffle'), ('blumpkin'), ('boang'), ('boche'), ('boches'), ('boffing'), ('bogan'), ('bohunk'), ('boink'), ('boiolas'), ('bollick'), ('bollock'), ('bollocks'), ('bollok'), ('bollox'), ('bombers'), ('bomd'), ('bondage'), ('boned'), ('boner'), ('boners'), ('bong'), ('boob'), ('boobies'), ('boobiez'), ('boobs'), ('boobz'), ('boong'), ('boonga'), ('boongas'), ('boongs'), ('boonie'), ('boonies'), ('booobs'), ('boooobs'), ('booooobs'), ('booooooobs'), ('bootlip'), ('bootlips'), ('bosch'), ('bosche'), ('bosches'), ('boschs'), ('bosomy'), ('bountybar'), ('bountybars'), ('breast'), ('breastjob'), ('breastlover'), ('breastman'), ('brownshower'), ('brownshowers'), ('brunetteaction') on conflict do nothing;
insert into public.name_words (word) values ('btch'), ('buceta'), ('buddhahead'), ('buddhaheads'), ('buffies'), ('bugger'), ('buggered'), ('buggery'), ('bukake'), ('bukkake'), ('bullcrap'), ('bulldike'), ('bulldyke'), ('bulletvibe'), ('bullshit'), ('bullshits'), ('bullshitted'), ('bullturds'), ('bumblefuck'), ('bumfuck'), ('bung'), ('bunga'), ('bungas'), ('bunghole'), ('bunnyfucker'), ('burrhead'), ('burrheads'), ('butchbabes'), ('butchdike'), ('butchdyke'), ('buttbang'), ('buttcheeks'), ('buttface'), ('buttfuck'), ('buttfucker'), ('buttfuckers'), ('butthead'), ('butthole'), ('buttman'), ('buttmuch'), ('buttmunch'), ('buttmuncher'), ('buttpirate'), ('buttplug'), ('buttstain'), ('buttwipe'), ('byatch'), ('cabron'), ('caca'), ('cacker'), ('cahone'), ('cameljockey'), ('cameljockeys'), ('cameltoe'), ('camgirl'), ('camslut'), ('camwhore'), ('carpetmuncher'), ('carruth'), ('cawk'), ('cawks'), ('cazzo'), ('chav'), ('cheeseeatingsurrendermonkey'), ('cheeseeatingsurrendermonkies'), ('cheesehead'), ('cheeseheads'), ('cherrypopper'), ('chickslick'), ('chinaman'), ('chinamen'), ('chinaswede'), ('chinaswedes'), ('chinc'), ('chincs'), ('chinga'), ('chingchong'), ('chingchongs'), ('chink'), ('chinks'), ('chinky'), ('choad'), ('chocolaterosebuds'), ('chode'), ('chodes'), ('chonkies'), ('chonky'), ('chonkys'), ('chraa'), ('christkiller'), ('christkillers'), ('chuj'), ('chunger'), ('chungers'), ('chunkies'), ('chunkys'), ('cipa'), ('circlejerk'), ('clamdigger'), ('clamdiver'), ('clansman'), ('clansmen'), ('clanswoman'), ('clanswomen'), ('clevelandsteamer'), ('clit'), ('clitface'), ('clitfuck'), ('clitoris'), ('clitorus'), ('clits'), ('clitty'), ('clogwog'), ('cloverclamps'), ('clusterfuck'), ('cnts'), ('cntz'), ('cnut'), ('cocain'), ('cocaine') on conflict do nothing;
insert into public.name_words (word) values ('cock'), ('cockbite'), ('cockblock'), ('cockblocker'), ('cockburger'), ('cockcowboy'), ('cockface'), ('cockfight'), ('cockfucker'), ('cockhead'), ('cockholster'), ('cockjockey'), ('cockknob'), ('cockknocker'), ('cockknoker'), ('cocklicker'), ('cocklover'), ('cockmaster'), ('cockmongler'), ('cockmongruel'), ('cockmonkey'), ('cockmunch'), ('cockmuncher'), ('cocknob'), ('cocknose'), ('cocknugget'), ('cockqueen'), ('cockrider'), ('cocks'), ('cockshit'), ('cocksman'), ('cocksmith'), ('cocksmoker'), ('cocksucer'), ('cocksuck'), ('cocksucked'), ('cocksucker'), ('cocksucking'), ('cocksucks'), ('cocksuka'), ('cocksukka'), ('cocktease'), ('cohee'), ('coital'), ('coitus'), ('cok'), ('cokmuncher'), ('coksucka'), ('condom'), ('coochie'), ('coochy'), ('coolie'), ('coolies'), ('cooly'), ('coonass'), ('coonasses'), ('coondog'), ('coons'), ('cooter'), ('coprolagnia'), ('coprophilia'), ('copulate'), ('corksucker'), ('cornhole'), ('crackcocain'), ('crackpipe'), ('crackwhore'), ('crapola'), ('crapper'), ('crappy'), ('creampie'), ('crotchjockey'), ('crotchmonkey'), ('crotchrot'), ('cuck'), ('cum'), ('cumbubble'), ('cumdumpster'), ('cumface'), ('cumfest'), ('cumguzzler'), ('cuming'), ('cumjockey'), ('cumlicker'), ('cumlickr'), ('cumm'), ('cummer'), ('cummin'), ('cumming'), ('cumquat'), ('cumqueen'), ('cums'), ('cumshot'), ('cumshots'), ('cumslut'), ('cumstain'), ('cumsucker'), ('cumtart'), ('cunilingus'), ('cunillingus'), ('cunn'), ('cunnie'), ('cunnilingus'), ('cunntt'), ('cunny'), ('cunt'), ('cunteyed'), ('cuntface'), ('cuntfuck'), ('cuntfucker'), ('cunthole'), ('cunthunter'), ('cuntlick'), ('cuntlicker'), ('cuntlicking'), ('cuntrag'), ('cunts'), ('cuntslut'), ('cuntsucker'), ('cuntz') on conflict do nothing;
insert into public.name_words (word) values ('currymuncher'), ('currymunchers'), ('cushi'), ('cushis'), ('cyalis'), ('cyberfuc'), ('cyberfuck'), ('cyberfucked'), ('cyberfucker'), ('cyberfuckers'), ('cyberfucking'), ('cybersex'), ('cyberslimer'), ('dago'), ('dagos'), ('dahmer'), ('damm'), ('dammit'), ('damnit'), ('darkey'), ('darkeys'), ('darkie'), ('darkies'), ('darky'), ('daterape'), ('datnigga'), ('dawgiestyle'), ('daygo'), ('deapthroat'), ('deepaction'), ('deepthroat'), ('deepthroating'), ('defecate'), ('deggo'), ('dego'), ('degos'), ('dendrophilia'), ('destroyyourpussy'), ('diaperdaddy'), ('diaperhead'), ('diaperheads'), ('dick'), ('dickbag'), ('dickbeater'), ('dickbeaters'), ('dickbrain'), ('dickdipper'), ('dickface'), ('dickflipper'), ('dickforbrains'), ('dickfuck'), ('dickhead'), ('dickheads'), ('dickhole'), ('dickish'), ('dickjuice'), ('dickless'), ('dicklick'), ('dicklicker'), ('dickman'), ('dickmilk'), ('dickmonger'), ('dickpic'), ('dickripper'), ('dicks'), ('dicksipper'), ('dickslap'), ('dickslicker'), ('dicksucker'), ('dickwad'), ('dickweasel'), ('dickweed'), ('dickwhipper'), ('dickwod'), ('dickzipper'), ('diddle'), ('dike'), ('dildo'), ('dildos'), ('dilf'), ('diligaf'), ('dilldo'), ('dilldos'), ('dillweed'), ('dingleberries'), ('dingleberry'), ('dink'), ('dinks'), ('dipship'), ('dipshit'), ('dipstick'), ('dirsa'), ('dirtypillows'), ('dirtysanchez'), ('dix'), ('dixiedike'), ('dixiedyke'), ('dlck'), ('dogfucker'), ('doggiestyle'), ('dogging'), ('doggystyle'), ('dogstyle'), ('dolcett'), ('dominatricks'), ('dominatrics'), ('dominatrix'), ('dommes'), ('dong'), ('donkeypunch'), ('donkeyribber'), ('doochbag'), ('doodoo'), ('dookie'), ('doosh'), ('dothead'), ('dotheads'), ('doubledong'), ('doublepenetration'), ('douche') on conflict do nothing;
insert into public.name_words (word) values ('douchebag'), ('douchebags'), ('douchefag'), ('douchewaffle'), ('douchey'), ('dpaction'), ('dragqueen'), ('dragqween'), ('dripdick'), ('dryhump'), ('duche'), ('dudette'), ('dumass'), ('dumbass'), ('dumbasses'), ('dumbbitch'), ('dumbfuck'), ('dumbshit'), ('dumshit'), ('dunecoon'), ('dunecoons'), ('dupa'), ('dvda'), ('dyefly'), ('dyke'), ('dykes'), ('dziwka'), ('earotics'), ('easyslut'), ('eatadick'), ('eatballs'), ('eathairpie'), ('eatme'), ('eatmy'), ('eatmyass'), ('eatpussy'), ('ecchi'), ('ejackulate'), ('ejakulate'), ('ekrem'), ('ekto'), ('enculer'), ('enema'), ('erection'), ('erotic'), ('erotism'), ('esqua'), ('essohbee'), ('ethicalslut'), ('excrement'), ('exkwew'), ('extacy'), ('extasy'), ('facefucker'), ('fack'), ('faeces'), ('faen'), ('fag'), ('fagbag'), ('faget'), ('fagfucker'), ('fagg'), ('fagged'), ('fagging'), ('faggit'), ('faggitt'), ('faggot'), ('faggotcock'), ('faggs'), ('fagit'), ('fagot'), ('fagots'), ('fags'), ('fagt'), ('fagtard'), ('fagz'), ('faig'), ('faigs'), ('faigt'), ('fanculo'), ('fanny'), ('fannybandit'), ('fannyflaps'), ('fannyfucker'), ('fanyy'), ('fartknocker'), ('fastfuck'), ('fatah'), ('fatfuck'), ('fatfucker'), ('fatso'), ('fck'), ('fckcum'), ('fckd'), ('fcuk'), ('fcuker'), ('fcuking'), ('fecal'), ('feck'), ('fecker'), ('feg'), ('felatio'), ('felch'), ('felcher'), ('felching'), ('fellate'), ('fellatio'), ('feltch'), ('feltcher'), ('feltching'), ('femalesquirtin'), ('femalesquirting'), ('femdom'), ('fetish'), ('ficken'), ('figging'), ('fingerbang'), ('fingerfood'), ('fingerfuck'), ('fingerfucked') on conflict do nothing;
insert into public.name_words (word) values ('fingerfucker'), ('fingerfuckers'), ('fingerfucking'), ('fingerfucks'), ('fingering'), ('fisted'), ('fister'), ('fistfuck'), ('fistfucked'), ('fistfucker'), ('fistfuckers'), ('fistfucking'), ('fistfuckings'), ('fistfucks'), ('fisting'), ('fisty'), ('fitt'), ('flamer'), ('flasher'), ('flikker'), ('flippingthebird'), ('flogthelog'), ('floozy'), ('flydie'), ('flydye'), ('foad'), ('fok'), ('fondle'), ('fook'), ('fooker'), ('footaction'), ('footfetish'), ('footfuck'), ('footfucker'), ('footjob'), ('footlicker'), ('footstar'), ('foreskin'), ('forni'), ('fornicate'), ('fotze'), ('foursome'), ('fourtwenty'), ('freakfuck'), ('freakyfucker'), ('freefuck'), ('freex'), ('frigg'), ('frigga'), ('frigger'), ('frotting'), ('fucck'), ('fuck'), ('fucka'), ('fuckable'), ('fuckass'), ('fuckbag'), ('fuckbitch'), ('fuckbook'), ('fuckboy'), ('fuckbrain'), ('fuckbuddy'), ('fuckbutt'), ('fuckd'), ('fucke'), ('fucked'), ('fuckedup'), ('fucker'), ('fuckers'), ('fuckersucker'), ('fuckface'), ('fuckfest'), ('fuckfreak'), ('fuckfriend'), ('fuckhead'), ('fuckheads'), ('fuckher'), ('fuckhole'), ('fuckin'), ('fuckina'), ('fucking'), ('fuckingbitch'), ('fuckings'), ('fuckingshitmotherfucker'), ('fuckinnuts'), ('fuckinright'), ('fuckit'), ('fuckknob'), ('fuckme'), ('fuckmeat'), ('fuckmehard'), ('fuckmonkey'), ('fuckn'), ('fucknugget'), ('fucknut'), ('fucknuts'), ('fucknutt'), ('fucknutz'), ('fuckoff'), ('fuckpig'), ('fuckpuppet'), ('fuckr'), ('fucks'), ('fuckstick'), ('fucktard'), ('fucktards'), ('fucktoy'), ('fucktrophy'), ('fuckup'), ('fuckwad'), ('fuckwhit'), ('fuckwhore'), ('fuckwit'), ('fuckwitt'), ('fuckyomama'), ('fuckyou'), ('fudgepacker'), ('fugly'), ('fuk'), ('fukah') on conflict do nothing;
insert into public.name_words (word) values ('fuken'), ('fuker'), ('fukin'), ('fuking'), ('fukk'), ('fukkah'), ('fukken'), ('fukker'), ('fukkin'), ('fukking'), ('fuks'), ('fuktard'), ('fuktards'), ('fukwhit'), ('fukwit'), ('funfuck'), ('futanari'), ('futanary'), ('futkretzn'), ('fuuck'), ('fux'), ('fuxor'), ('fvck'), ('fvk'), ('fxck'), ('gae'), ('gangbang'), ('gangbanged'), ('gangbanger'), ('gangbangs'), ('ganja'), ('gassyass'), ('gatorbait'), ('gayass'), ('gaybob'), ('gayboy'), ('gaydo'), ('gaygirl'), ('gaylord'), ('gaymuthafuckinwhore'), ('gays'), ('gaysex'), ('gaytard'), ('gaywad'), ('gayz'), ('genital'), ('genitals'), ('getiton'), ('gey'), ('gfy'), ('ghay'), ('ghey'), ('giantcock'), ('gigolo'), ('ginzo'), ('ginzos'), ('gipp'), ('gippo'), ('gippos'), ('gipps'), ('girlon'), ('girlontop'), ('girlsgonewild'), ('girlsicup'), ('givehead'), ('glans'), ('glazeddonut'), ('goatcx'), ('goatse'), ('godam'), ('godammit'), ('godamn'), ('godamnit'), ('goddam'), ('goddamit'), ('goddamm'), ('goddammit'), ('goddamn'), ('goddamned'), ('goddamnes'), ('goddamnit'), ('goddamnmuthafucker'), ('godsdamn'), ('gokkun'), ('goldenshower'), ('golliwog'), ('golliwogs'), ('gonad'), ('gonads'), ('gonorrehea'), ('gonzagas'), ('gooch'), ('goodpoop'), ('googirl'), ('gook'), ('gookeye'), ('gookeyes'), ('gookies'), ('gooks'), ('gooky'), ('gora'), ('goras'), ('goregasm'), ('gotohell'), ('goy'), ('goyim'), ('greaseball'), ('greaseballs'), ('groid'), ('groids'), ('grope'), ('grostulation'), ('groupsex'), ('gspot'), ('gstring'), ('gtfo'), ('gubba'), ('gubbas'), ('gubs'), ('guido') on conflict do nothing;
insert into public.name_words (word) values ('guiena'), ('guineas'), ('guizi'), ('gummer'), ('guro'), ('gwailo'), ('gwailos'), ('gweilo'), ('gweilos'), ('gyopo'), ('gyopos'), ('gyp'), ('gyped'), ('gypo'), ('gypos'), ('gypp'), ('gypped'), ('gyppie'), ('gyppies'), ('gyppo'), ('gyppos'), ('gyppy'), ('gyppys'), ('gypsys'), ('hadji'), ('hadjis'), ('hairyback'), ('hairybacks'), ('haji'), ('hajis'), ('hajji'), ('hajjis'), ('halfbreed'), ('halfcaste'), ('hamas'), ('hamflap'), ('handjob'), ('haole'), ('haoles'), ('hardcore'), ('hardcoresex'), ('hardon'), ('haxor'), ('headfuck'), ('hebe'), ('hebes'), ('heeb'), ('heebs'), ('heii'), ('helvete'), ('hentai'), ('heroin'), ('herp'), ('herpes'), ('herpy'), ('heshe'), ('hijacking'), ('hillbillies'), ('hillbilly'), ('hindoo'), ('hiscock'), ('hitler'), ('hitlerism'), ('hitlerist'), ('hoar'), ('hoare'), ('hobag'), ('hodgie'), ('hoer'), ('hoes'), ('holestuffer'), ('homo'), ('homobangers'), ('homodumbshit'), ('homoey'), ('honger'), ('honkers'), ('honkey'), ('honkeys'), ('honkie'), ('honkies'), ('honky'), ('hooker'), ('hookers'), ('hoor'), ('hoore'), ('hootch'), ('hooter'), ('hooters'), ('hore'), ('hori'), ('horis'), ('hork'), ('horndawg'), ('horndog'), ('horney'), ('horniest'), ('horny'), ('horseshit'), ('hosejob'), ('hotcarl'), ('hotchick'), ('hotdamn'), ('hotpussy'), ('hotsex'), ('hottotrot'), ('howtokill'), ('howtomurdep'), ('howtomurder'), ('huevon'), ('hugefat'), ('humped'), ('humper'), ('humpher'), ('humphim'), ('humpin'), ('humping'), ('hussy'), ('hustler'), ('hymen') on conflict do nothing;
insert into public.name_words (word) values ('hymie'), ('hymies'), ('iblowu'), ('ikes'), ('ikey'), ('ikeymo'), ('ikeymos'), ('ikwe'), ('illegals'), ('incest'), ('indon'), ('indons'), ('injun'), ('injuns'), ('insest'), ('intercourse'), ('intheass'), ('inthebuff'), ('israels'), ('jackass'), ('jackhole'), ('jackoff'), ('jackshit'), ('jacktheripper'), ('jailbait'), ('jap'), ('japcrap'), ('japie'), ('japies'), ('japs'), ('jebus'), ('jellydonut'), ('jerked'), ('jerkoff'), ('jerries'), ('jewboy'), ('jewed'), ('jewess'), ('jiga'), ('jigaboo'), ('jigaboos'), ('jigarooni'), ('jigaroonis'), ('jigg'), ('jigga'), ('jiggabo'), ('jiggaboo'), ('jiggabos'), ('jiggas'), ('jiggerboo'), ('jiggers'), ('jiggs'), ('jigs'), ('jihad'), ('jijjiboo'), ('jijjiboos'), ('jimfish'), ('jisim'), ('jism'), ('jiss'), ('jiz'), ('jizim'), ('jizin'), ('jizjuice'), ('jizm'), ('jizn'), ('jizz'), ('jizzd'), ('jizzed'), ('jizzim'), ('jizzin'), ('jizzn'), ('jizzum'), ('jugg'), ('juggs'), ('junglebunnies'), ('junglebunny'), ('junky'), ('kacap'), ('kacapas'), ('kacaps'), ('kaffer'), ('kaffir'), ('kaffre'), ('kafir'), ('kanake'), ('kanker'), ('katsap'), ('katsaps'), ('kawk'), ('khokhol'), ('khokhols'), ('kigger'), ('kike'), ('kikes'), ('kimchis'), ('kinbaku'), ('kink'), ('kinkster'), ('kinky'), ('kinkyjesus'), ('kissass'), ('kiunt'), ('kkk'), ('klan'), ('klansman'), ('klansmen'), ('klanswoman'), ('klanswomen'), ('klootzak'), ('knobbing'), ('knobead'), ('knobed'), ('knobend'), ('knobhead'), ('knobjocky'), ('knobjokey'), ('knobz'), ('knockers'), ('knulle') on conflict do nothing;
insert into public.name_words (word) values ('kock'), ('kondum'), ('kondums'), ('kooch'), ('kooches'), ('koon'), ('kootch'), ('krap'), ('krappy'), ('kraut'), ('krauts'), ('kuffar'), ('kuk'), ('kuksuger'), ('kum'), ('kumbubble'), ('kumbullbe'), ('kumer'), ('kummer'), ('kumming'), ('kums'), ('kunilingus'), ('kunnilingus'), ('kunt'), ('kunts'), ('kuntz'), ('kurac'), ('kurwa'), ('kushi'), ('kushis'), ('kusi'), ('kwailo'), ('kwailos'), ('kwif'), ('kyke'), ('kykes'), ('kyopo'), ('kyopos'), ('kyrpa'), ('labia'), ('lapdance'), ('leatherrestraint'), ('leatherstraight'), ('lebos'), ('lech'), ('leitch'), ('lemonparty'), ('lesbain'), ('lesbayn'), ('lesbin'), ('lesbo'), ('lesbos'), ('lez'), ('lezbe'), ('lezbefriends'), ('lezbian'), ('lezbians'), ('lezbo'), ('lezbos'), ('lezz'), ('lezzian'), ('lezzie'), ('lezzies'), ('lezzo'), ('lezzy'), ('libido'), ('licking'), ('lickme'), ('lilniglet'), ('limey'), ('limpdick'), ('limy'), ('lingerie'), ('lipshits'), ('lipshitz'), ('livesex'), ('loadedgun'), ('lolita'), ('lovebone'), ('lovegoo'), ('lovegun'), ('lovejuice'), ('lovemuscle'), ('lovepistol'), ('loverocket'), ('lowlife'), ('lubejob'), ('lubra'), ('lucifer'), ('luckycammeltoe'), ('lugan'), ('lugans'), ('lusting'), ('mabuno'), ('mabunos'), ('macaca'), ('macacas'), ('mafugly'), ('magicwand'), ('mahbuno'), ('mahbunos'), ('makemecome'), ('makemecum'), ('malesquirting'), ('mamhoon'), ('mams'), ('manhater'), ('manpaste'), ('maricn'), ('maricon'), ('marijuana'), ('masochist'), ('masokist'), ('massterbait'), ('masstrbait'), ('masstrbate'), ('mastabate'), ('mastabater'), ('masterbaiter'), ('masterbat') on conflict do nothing;
insert into public.name_words (word) values ('masterbate'), ('masterbates'), ('masterbating'), ('masterbation'), ('masterbations'), ('masterbb'), ('masterblaster'), ('mastrabator'), ('masturbat'), ('masturbate'), ('masturbating'), ('masturbation'), ('mattressprincess'), ('maumau'), ('maumaus'), ('mcfagget'), ('meatbeatter'), ('meatrack'), ('menage'), ('merd'), ('mfucking'), ('mgger'), ('mggor'), ('mibun'), ('mickeyfinn'), ('mideast'), ('mierda'), ('milf'), ('mindfuck'), ('minge'), ('minger'), ('mockey'), ('mockie'), ('mocky'), ('mofo'), ('moky'), ('molest'), ('molestation'), ('molester'), ('molestor'), ('moneyshot'), ('mong'), ('monkleigh'), ('moolie'), ('mooncricket'), ('mooncrickets'), ('moron'), ('moskal'), ('moskals'), ('moslem'), ('mosshead'), ('mothafuck'), ('mothafucka'), ('mothafuckas'), ('mothafuckaz'), ('mothafucked'), ('mothafucker'), ('mothafuckers'), ('mothafuckin'), ('mothafucking'), ('mothafuckings'), ('mothafucks'), ('mothafuker'), ('mothafukkah'), ('mothafukker'), ('motherfuck'), ('motherfucka'), ('motherfucked'), ('motherfucker'), ('motherfuckers'), ('motherfuckin'), ('motherfucking'), ('motherfuckings'), ('motherfuckka'), ('motherfucks'), ('motherfukah'), ('motherfuker'), ('motherfukkah'), ('motherfukker'), ('motherfvcker'), ('motherlovebone'), ('mothrfucker'), ('mouliewop'), ('moundofvenus'), ('mrhands'), ('mtherfucker'), ('mthrfuck'), ('mthrfucker'), ('mthrfucking'), ('mtrfck'), ('mtrfuck'), ('mtrfucker'), ('muff'), ('muffdive'), ('muffdiver'), ('muffdiving'), ('muffindiver'), ('mufflikcer'), ('muffpuff'), ('muie'), ('mulatto'), ('mulkku'), ('muncher'), ('munging'), ('munt'), ('munter'), ('muschi'), ('muthafecker'), ('muthafuckaz'), ('muthafucker'), ('muthafuckker'), ('muthafukah'), ('muthafuker'), ('muthafukkah'), ('muthafukker'), ('muther'), ('mutherfucker'), ('mutherfucking'), ('muthrfucking'), ('mzungu') on conflict do nothing;
insert into public.name_words (word) values ('mzungus'), ('nads'), ('naked'), ('nambla'), ('nastt'), ('nastybitch'), ('nastyho'), ('nastyslut'), ('nastywhore'), ('nawashi'), ('nazi'), ('nazis'), ('nazism'), ('necro'), ('needthedick'), ('negres'), ('negress'), ('negro'), ('negroes'), ('negroid'), ('negros'), ('neonazi'), ('nepesaurio'), ('nig'), ('niga'), ('nigar'), ('nigars'), ('nigas'), ('nigers'), ('nigette'), ('nigettes'), ('nigg'), ('nigga'), ('niggah'), ('niggahs'), ('niggar'), ('niggaracci'), ('niggard'), ('niggarded'), ('niggarding'), ('niggardliness'), ('niggardlinesss'), ('niggardly'), ('niggards'), ('niggars'), ('niggas'), ('niggaz'), ('nigger'), ('niggerhead'), ('niggerhole'), ('niggers'), ('niggled'), ('niggles'), ('nigglings'), ('niggor'), ('niggress'), ('niggresses'), ('nigguh'), ('nigguhs'), ('niggur'), ('niggurs'), ('niglet'), ('nignog'), ('nigor'), ('nigors'), ('nigr'), ('nigra'), ('nigras'), ('nigre'), ('nigres'), ('nigress'), ('nigs'), ('nigur'), ('niiger'), ('niigr'), ('nimphomania'), ('nipple'), ('nipplering'), ('nipples'), ('nips'), ('nittit'), ('nlgger'), ('nlggor'), ('nobhead'), ('nobjocky'), ('nobjokey'), ('nofuckingway'), ('nookey'), ('nookie'), ('nooky'), ('nooner'), ('nsfw'), ('nsfwimages'), ('nudger'), ('nudie'), ('nudies'), ('numbnuts'), ('nutbutter'), ('nutfucker'), ('nutsack'), ('nutten'), ('nympho'), ('nymphomania'), ('octopussy'), ('omorashi'), ('onecuptwogirls'), ('oneguyonejar'), ('ontherag'), ('orafis'), ('orgasim'), ('orgasims'), ('orgasm'), ('orgasmic'), ('orgasms'), ('orgasum'), ('orgies'), ('orgy'), ('oriface'), ('orifiss'), ('orospu') on conflict do nothing;
insert into public.name_words (word) values ('osama'), ('ovum'), ('ovums'), ('packi'), ('packie'), ('packy'), ('paedophile'), ('paki'), ('pakie'), ('pakis'), ('paky'), ('palesimian'), ('pancakeface'), ('pancakefaces'), ('panooch'), ('pansies'), ('pansy'), ('panti'), ('pantie'), ('panties'), ('panty'), ('paska'), ('payo'), ('pearlnecklace'), ('pecker'), ('peckerhead'), ('peckerwood'), ('pedo'), ('pedobear'), ('pedophile'), ('pedophilia'), ('pedophiliac'), ('peeenus'), ('peeenusss'), ('peehole'), ('peenus'), ('peepee'), ('peepshow'), ('peepshpw'), ('pegging'), ('peinus'), ('penas'), ('pendejo'), ('pendy'), ('penetrate'), ('penetration'), ('penial'), ('penile'), ('penis'), ('penisbreath'), ('penises'), ('penisfucker'), ('penisland'), ('penislick'), ('penislicker'), ('penispuffer'), ('penthouse'), ('penus'), ('penuus'), ('perv'), ('perversion'), ('peyote'), ('phalli'), ('phallic'), ('phonesex'), ('phuc'), ('phuck'), ('phuk'), ('phuked'), ('phuker'), ('phuking'), ('phukked'), ('phukker'), ('phukking'), ('phuks'), ('phungky'), ('phuq'), ('picaninny'), ('piccaninny'), ('picka'), ('pickaninnies'), ('pickaninny'), ('pieceofshit'), ('piefke'), ('piefkes'), ('pierdol'), ('pigfucker'), ('piker'), ('pikey'), ('piky'), ('pillowbiter'), ('pillu'), ('pimmel'), ('pimp'), ('pimped'), ('pimper'), ('pimpis'), ('pimpjuic'), ('pimpjuice'), ('pimpsimp'), ('pindick'), ('pinko'), ('pis'), ('pises'), ('pisin'), ('pising'), ('pisof'), ('piss'), ('pissed'), ('pisser'), ('pissers'), ('pisses'), ('pissflap'), ('pissflaps'), ('pisshead'), ('pissin'), ('pissing'), ('pissoff'), ('pisspig'), ('pizda') on conflict do nothing;
insert into public.name_words (word) values ('playboy'), ('playgirl'), ('pleasurechest'), ('pocha'), ('pochas'), ('pocho'), ('pochos'), ('pocketpool'), ('pohm'), ('pohms'), ('polac'), ('polack'), ('polacks'), ('polak'), ('polesmoker'), ('pollock'), ('pollocks'), ('pommiegrant'), ('pommiegrants'), ('pommy'), ('ponyplay'), ('poof'), ('poon'), ('poonani'), ('poonany'), ('poontang'), ('poontsee'), ('poopchute'), ('pooper'), ('pooperscooper'), ('pooping'), ('poorwhitetrash'), ('popimp'), ('porchmonkey'), ('porchmonkies'), ('porn'), ('pornflick'), ('pornking'), ('porno'), ('pornography'), ('pornos'), ('pornprincess'), ('poundtown'), ('pplicker'), ('prairienigger'), ('prairieniggers'), ('preteen'), ('pric'), ('prick'), ('prickhead'), ('pricks'), ('prig'), ('prik'), ('princealbertpiercing'), ('pron'), ('prostitute'), ('pthc'), ('pube'), ('pubes'), ('pubic'), ('pubiclice'), ('pubis'), ('pudboy'), ('pudd'), ('puddboy'), ('pula'), ('punani'), ('punanny'), ('punany'), ('punkass'), ('punta'), ('puntang'), ('purinapricness'), ('pusies'), ('puss'), ('pusse'), ('pussee'), ('pussi'), ('pussie'), ('pussies'), ('pussy'), ('pussycat'), ('pussydestroyer'), ('pussyeater'), ('pussyfart'), ('pussyfuck'), ('pussyfucker'), ('pussylicker'), ('pussylicking'), ('pussylips'), ('pussylover'), ('pussypalace'), ('pussypounder'), ('pussys'), ('pusy'), ('puta'), ('puto'), ('puuke'), ('puuker'), ('qahbeh'), ('quashie'), ('queaf'), ('queef'), ('queerhole'), ('queero'), ('queers'), ('queerz'), ('quickie'), ('quiff'), ('quim'), ('qweers'), ('qweerz'), ('qweir'), ('rabs'), ('raghead'), ('ragheads'), ('rape'), ('raped'), ('raper'), ('raping') on conflict do nothing;
insert into public.name_words (word) values ('rapist'), ('rautenberg'), ('rearend'), ('rearentry'), ('recktum'), ('rectal'), ('rectum'), ('rectus'), ('redlegs'), ('redlight'), ('redskin'), ('redskins'), ('reefer'), ('reestie'), ('reetard'), ('reich'), ('renob'), ('rentafuck'), ('retard'), ('retarded'), ('retards'), ('retardz'), ('reversecowgirl'), ('rimjaw'), ('rimjob'), ('rimming'), ('ritard'), ('rosebuds'), ('rosypalm'), ('rosypalmandherefivesisters'), ('rosypalmandherssisters'), ('roundeye'), ('roundeyes'), ('rtard'), ('rtards'), ('rumprammer'), ('ruski'), ('russki'), ('russkie'), ('rustytrombone'), ('sadis'), ('sadism'), ('sadist'), ('sadom'), ('sambo'), ('sambos'), ('samckdaddy'), ('sanchez'), ('sandm'), ('sandnigger'), ('sandniggers'), ('santorum'), ('sausagequeen'), ('scag'), ('scallywag'), ('scank'), ('scantily'), ('scat'), ('schaffer'), ('scheiss'), ('schizo'), ('schlampe'), ('schlong'), ('schmuck'), ('schvartse'), ('schvartsen'), ('schwartze'), ('schwartzen'), ('scissoring'), ('screwyou'), ('scroat'), ('scrog'), ('scrote'), ('scrotum'), ('scrud'), ('semen'), ('seppo'), ('seppos'), ('septics'), ('sex'), ('sexcam'), ('sexed'), ('sexfarm'), ('sexhound'), ('sexhouse'), ('sexi'), ('sexing'), ('sexkitten'), ('sexo'), ('sexpot'), ('sexslave'), ('sextogo'), ('sextoy'), ('sextoys'), ('sexual'), ('sexually'), ('sexwhore'), ('sexx'), ('sexxi'), ('sexxx'), ('sexxxi'), ('sexxxy'), ('sexxy'), ('sexy'), ('sexymoma'), ('sexyslim'), ('shag'), ('shagger'), ('shaggin'), ('shagging'), ('shamedame'), ('sharmuta'), ('sharmute'), ('shat'), ('shav'), ('shavedbeaver'), ('shavedpussy'), ('shawtypimp'), ('sheeney'), ('shemale') on conflict do nothing;
insert into public.name_words (word) values ('shhit'), ('shibari'), ('shibary'), ('shinola'), ('shipal'), ('shit'), ('shitass'), ('shitbag'), ('shitbagger'), ('shitblimp'), ('shitbrain'), ('shitbreath'), ('shitcan'), ('shitcunt'), ('shitdick'), ('shite'), ('shiteater'), ('shiteating'), ('shited'), ('shiter'), ('shitey'), ('shitface'), ('shitfaced'), ('shitfit'), ('shitforbrains'), ('shitfuck'), ('shitfucker'), ('shitfull'), ('shithapens'), ('shithappens'), ('shithead'), ('shitheel'), ('shithole'), ('shithouse'), ('shiting'), ('shitings'), ('shitlist'), ('shitload'), ('shitola'), ('shitoutofluck'), ('shitpot'), ('shits'), ('shitspitter'), ('shitstain'), ('shitt'), ('shitted'), ('shitter'), ('shitters'), ('shittiest'), ('shitting'), ('shittings'), ('shitty'), ('shity'), ('shitz'), ('shiz'), ('shiznit'), ('shortfuck'), ('shota'), ('sht'), ('shylock'), ('shylocks'), ('shyt'), ('shyte'), ('shytty'), ('shyty'), ('simp'), ('sissy'), ('sixsixsix'), ('sixtynine'), ('sixtyniner'), ('skag'), ('skanck'), ('skank'), ('skankbitch'), ('skankee'), ('skankey'), ('skankfuck'), ('skanks'), ('skankwhore'), ('skanky'), ('skankybitch'), ('skankywhore'), ('skeet'), ('skinflute'), ('skribz'), ('skullfuck'), ('skum'), ('skumbag'), ('skurwysyn'), ('skwa'), ('skwe'), ('slag'), ('slanteye'), ('slanty'), ('slapper'), ('sleezeball'), ('slideitin'), ('slimeball'), ('slimebucket'), ('slopehead'), ('slopeheads'), ('slopers'), ('slopey'), ('slopeys'), ('slopies'), ('slopy'), ('slut'), ('slutbag'), ('slutbucket'), ('slutdumper'), ('slutkiss'), ('sluts'), ('slutt'), ('slutting'), ('slutty'), ('slutwear'), ('slutwhore'), ('slutz'), ('smackthemonkey'), ('smeg') on conflict do nothing;
insert into public.name_words (word) values ('smegma'), ('smut'), ('smutty'), ('snatchpatch'), ('sniggered'), ('sniggering'), ('sniggers'), ('snowback'), ('snowballing'), ('snownigger'), ('socksucker'), ('sodom'), ('sodomise'), ('sodomite'), ('sodomize'), ('sodomy'), ('sonofabitch'), ('sonofawhore'), ('sonofbitch'), ('sooties'), ('souse'), ('soused'), ('soyboy'), ('spac'), ('spaghettibender'), ('spaghettinigger'), ('spank'), ('spankthemonkey'), ('spastic'), ('spearchucker'), ('spearchuckers'), ('sperm'), ('spermacide'), ('spermbag'), ('spermhearder'), ('spermherder'), ('sphencter'), ('spic'), ('spick'), ('spicks'), ('spics'), ('spierdalaj'), ('spig'), ('spigotty'), ('spik'), ('spiks'), ('splittail'), ('splooge'), ('spludge'), ('spooge'), ('spreadeagle'), ('spreadlegs'), ('spunk'), ('spunky'), ('sqeh'), ('squa'), ('squarehead'), ('squareheads'), ('squaw'), ('squinty'), ('squirting'), ('stagg'), ('stfu'), ('stiffy'), ('strapon'), ('strappado'), ('stripclub'), ('stroking'), ('stuinties'), ('stupidfuck'), ('stupidfucker'), ('styledoggy'), ('suckdick'), ('sucking'), ('suckme'), ('suckmyass'), ('suckmydick'), ('suckmytit'), ('suckoff'), ('suicidegirl'), ('suicidegirls'), ('suka'), ('sultrywoman'), ('sultrywomen'), ('sumofabiatch'), ('swallower'), ('swalow'), ('swampguinea'), ('swampguineas'), ('swastika'), ('syphilis'), ('tacohead'), ('tacoheads'), ('takeoffyour'), ('tarbabies'), ('tarbaby'), ('tard'), ('tastemy'), ('teabagging'), ('teat'), ('teets'), ('teez'), ('terd'), ('testes'), ('testical'), ('testicle'), ('testicles'), ('testis'), ('thicklip'), ('thicklips'), ('thirdeye'), ('thirdleg'), ('threesome'), ('threeway'), ('throating'), ('thumbzilla'), ('thundercunt'), ('tightwhite'), ('tigolbitties'), ('tigoldbitties') on conflict do nothing;
insert into public.name_words (word) values ('timbernigger'), ('timberniggers'), ('tit'), ('titbitnipply'), ('titfuck'), ('titfucker'), ('titfuckin'), ('titjob'), ('titlicker'), ('titlover'), ('tits'), ('titt'), ('tittie'), ('tittiefucker'), ('titties'), ('tittis'), ('titty'), ('tittyfuck'), ('tittyfucker'), ('tittys'), ('tittywank'), ('titwank'), ('tity'), ('tomurder'), ('tongethruster'), ('tongueina'), ('tonguethrust'), ('tonguetramp'), ('topless'), ('tortur'), ('torture'), ('tosser'), ('towelhead'), ('towelheads'), ('trailertrash'), ('trannie'), ('tranny'), ('transsexual'), ('transvestite'), ('tribadism'), ('trisexual'), ('troon'), ('troons'), ('trots'), ('tubgirl'), ('tuckahoe'), ('tunneloflove'), ('turdburgler'), ('tush'), ('tushy'), ('twat'), ('twathead'), ('twatlips'), ('twats'), ('twatty'), ('twatwaffle'), ('twink'), ('twinkie'), ('twobitwhore'), ('twogirlsonecup'), ('twunt'), ('twunter'), ('udgepacker'), ('ukrop'), ('unclefucker'), ('unfuckable'), ('upskirt'), ('uptheass'), ('upthebutt'), ('urethraplay'), ('urophilia'), ('usama'), ('ussys'), ('vag'), ('vagiina'), ('vagina'), ('vagra'), ('vaijina'), ('vajina'), ('vajj'), ('valium'), ('venusmound'), ('vgra'), ('viagra'), ('vibr'), ('vibrater'), ('vibrator'), ('vigra'), ('violetwand'), ('virginbreaker'), ('vittu'), ('vjayjay'), ('vorarephilia'), ('voyeurweb'), ('voyuer'), ('vullva'), ('vulva'), ('wank'), ('wanker'), ('wanking'), ('wanky'), ('waysted'), ('weenie'), ('weewee'), ('weiner'), ('welcher'), ('wench'), ('wetb'), ('wetback'), ('wetbacks'), ('wetdream'), ('wetspot'), ('whacker'), ('whash'), ('whigger'), ('whiggers'), ('whiskeydick'), ('whiskydick'), ('whitenigger'), ('whitepower') on conflict do nothing;
insert into public.name_words (word) values ('whitetrash'), ('whitey'), ('whiteys'), ('whities'), ('whoar'), ('whoor'), ('whop'), ('whoralicious'), ('whore'), ('whorealicious'), ('whorebag'), ('whored'), ('whoreface'), ('whorefucker'), ('whorehopper'), ('whorehouse'), ('whores'), ('whoring'), ('wichser'), ('wigga'), ('wiggas'), ('wigger'), ('wiggers'), ('willie'), ('willies'), ('williewanker'), ('wog'), ('wogs'), ('woose'), ('wop'), ('worldsex'), ('wrappingmen'), ('wrinkledstarfish'), ('wtf'), ('wuss'), ('wuzzie'), ('xkwe'), ('xrated'), ('xratedgic'), ('xtc'), ('xxx'), ('xxxxxx'), ('yaoi'), ('yarpie'), ('yarpies'), ('yellowman'), ('yellowshowers'), ('yid'), ('yids'), ('yiffy'), ('yobbo'), ('yourboobs'), ('yourpenis'), ('yourtits'), ('yury'), ('zabourah'), ('zigabo'), ('zigabos'), ('zipperhead'), ('zipperheads'), ('zoophile'), ('zoophilia') on conflict do nothing;
-- END WORDS

create or replace function public.name_blocked(p_name text) returns boolean
language sql stable security definer set search_path = public as $$
  with raw as (
    select w, i
    from unnest(regexp_split_to_array(lower(regexp_replace(coalesce(p_name, ''), '([a-z])([A-Z])', '\1 \2', 'g')), '[ _-]+'))
      with ordinality as t(w, i)
    where w <> ''
  ), forms as (
    select i, regexp_replace(translate(w, '0134578', 'oieastb'), '[^a-z]', '', 'g') as leet,
              regexp_replace(w, '[^a-z]', '', 'g') as plain
    from raw
  ), whole as (
    select string_agg(leet, '' order by i) as c from forms
    union all
    select string_agg(plain, '' order by i) from forms
  )
  select exists (select 1 from public.name_words n where n.word in (select leet from forms union select plain from forms))
      or exists (select 1 from public.name_words n, whole where n.word = whole.c or (n.strong and position(n.word in whole.c) > 0));
$$;

revoke execute on function public.name_blocked from public, anon, authenticated;

-- set_pilot_name, as before (0003), and now refusing blocked names.
create or replace function public.set_pilot_name(p_name text) returns text
language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  clean text := btrim(coalesce(p_name, ''));
  changed timestamptz;
begin
  if me is null then raise exception 'sign in first' using errcode = '28000'; end if;
  if clean !~ '^[A-Za-z0-9_ -]{3,16}$' then
    raise exception 'use 3 to 16 letters, numbers, spaces, - or _' using errcode = '22023';
  end if;
  if public.name_blocked(clean) then
    raise exception 'that name isn''t allowed. try another' using errcode = '22023';
  end if;
  if exists (select 1 from public.players where lower(name) = lower(clean) and user_id <> me) then
    raise exception 'that name is taken' using errcode = '22023';
  end if;
  select name_changed_at into changed from public.players where user_id = me;
  if changed is not null and now() - changed < interval '1 hour' then
    raise exception 'you can change your name once an hour' using errcode = '22023';
  end if;
  update public.players set name = clean, name_changed_at = now() where user_id = me;
  return clean;
end $$;

revoke execute on function public.set_pilot_name from public, anon;
grant execute on function public.set_pilot_name to authenticated;

-- ===== 0010_secure_cores.sql =====

-- Cores can only come from real rewards (assessment items 1 and 2).
--
-- 1. grant_cores pays any account any amount, for the purchase webhook (which
--    uses the service key). 0001 revoked it from anon and authenticated, but
--    Postgres gives every function to PUBLIC too, so players could still call
--    it. Revoke that as well.
-- 2. earn_cores trusted the client up to 120 a day. Now every reward names
--    itself ("login:2026-10-07", "pass:3:p10", "set:forge"...), is paid at most
--    once, at most its real size, and only for the current day, week or season.

revoke execute on function public.grant_cores from public, anon, authenticated;
revoke execute on function public.earn_cores, public.spend_cores from public, anon;
grant execute on function public.earn_cores, public.spend_cores to authenticated;

create index if not exists core_log_reason on public.core_log (user_id, reason);

create or replace function public.earn_cores(amount integer, reason text) returns integer
language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  kind text := split_part(coalesce(reason, ''), ':', 1);
  rest text := substr(coalesce(reason, ''), length(split_part(coalesce(reason, ''), ':', 1)) + 2);
  today date := (now() at time zone 'utc')::date;
  season integer := floor((today - date '2026-09-14') / 42) + 1; -- six-week seasons (src/season.ts)
  most integer;
  give integer;
  so_far integer;
begin
  if me is null or amount is null or amount <= 0 then return 0; end if;
  -- Each reward is paid once.
  if exists (select 1 from public.core_log l where l.user_id = me and l.reason = earn_cores.reason) then return 0; end if;

  if kind in ('login', 'gift', 'goals', 'weekly') then
    -- A UTC date: today's (a day either side for clocks and midnight), or this week's Monday.
    if rest !~ '^\d{4}-\d{2}-\d{2}$' then return 0; end if;
    if kind = 'weekly' then
      if rest::date not between today - 8 and today + 1 then return 0; end if;
    elsif rest::date not between today - 1 and today + 1 then
      return 0;
    end if;
    most := case kind when 'login' then 15 when 'gift' then 2 when 'goals' then 4 else 15 end;
  elsif kind = 'pass' then
    -- "pass:<season>:<f|p><tier>", this season, and no more than the whole pass pays.
    if rest !~ ('^' || season || ':[fp]([1-9]|[12][0-9]|30)$') then return 0; end if;
    select coalesce(sum(l.delta), 0) into so_far from public.core_log l
      where l.user_id = me and l.reason like 'pass:' || season || ':%';
    most := least(50, 300 - so_far);
  elsif kind = 'set' then
    -- A completed looks set's bonus (SETS in src/catalogue.ts).
    if rest not in ('forge', 'deep', 'neon', 'royal', 'toxic', 'sunset') then return 0; end if;
    most := 40;
  elsif kind = 'tickets' and rest = '' then
    most := 300; -- the one-off refund for spare ranked tickets (src/legacy.ts)
  else
    return 0;
  end if;

  give := greatest(0, least(amount, most));
  if give = 0 then return 0; end if;
  update public.wallets set cores = cores + give where user_id = me;
  if not found then return 0; end if;
  insert into public.core_log (user_id, delta, reason) values (me, give, earn_cores.reason);
  return give;
end $$;

revoke execute on function public.earn_cores from public, anon;
grant execute on function public.earn_cores to authenticated;

-- ===== 0011_store_purchases.sql =====

-- Purchases, safely (assessment items 4 and 5).
--
-- store_purchase: the webhook's one call per paid event. Keeping the event and
-- paying its cores happen in one transaction, so a failure leaves nothing
-- behind and RevenueCat's retry pays it properly; a repeat of an event that
-- went through answers 'duplicate'.
--
-- store_refund: a refunded purchase. Its row is renamed 'refunded:<product>',
-- so premium and the starter pack stop counting everywhere that looks for the
-- product (the boards' badge, the game's purchases()), and refunded cores are
-- taken back (the balance can't go below zero).
-- Both are for the webhook's service key only.

alter table public.store_events add column if not exists transaction_id text;

create or replace function public.store_purchase(p_id text, p_user uuid, p_product text, p_type text, p_transaction text, p_cores integer)
returns text language plpgsql security definer set search_path = public as $$
begin
  insert into public.store_events (id, user_id, product, type, transaction_id)
  values (p_id, p_user, p_product, p_type, p_transaction)
  on conflict (id) do nothing;
  if not found then return 'duplicate'; end if;
  if p_user is not null and coalesce(p_cores, 0) > 0 then
    insert into public.wallets (user_id, cores) values (p_user, p_cores)
      on conflict (user_id) do update set cores = public.wallets.cores + p_cores;
    insert into public.core_log (user_id, delta, reason) values (p_user, p_cores, 'purchase:' || p_product);
  end if;
  return 'paid';
end $$;

create or replace function public.store_refund(p_id text, p_user uuid, p_product text, p_transaction text, p_cores integer)
returns text language plpgsql security definer set search_path = public as $$
declare
  bought text;
begin
  insert into public.store_events (id, user_id, product, type, transaction_id)
  values (p_id, p_user, 'refund:' || p_product, 'CANCELLATION', p_transaction)
  on conflict (id) do nothing;
  if not found then return 'duplicate'; end if;
  select e.id into bought from public.store_events e
    where e.product = p_product and e.user_id is not distinct from p_user
      and (p_transaction is null or e.transaction_id is null or e.transaction_id = p_transaction)
    order by (e.transaction_id = p_transaction) desc nulls last, e.at desc
    limit 1;
  if bought is null then return 'not found'; end if;
  update public.store_events set product = 'refunded:' || product where id = bought;
  if p_user is not null and coalesce(p_cores, 0) > 0 then
    update public.wallets set cores = greatest(0, cores - p_cores) where user_id = p_user;
    insert into public.core_log (user_id, delta, reason) values (p_user, -p_cores, 'refund:' || p_product);
  end if;
  return 'refunded';
end $$;

revoke execute on function public.store_purchase, public.store_refund from public, anon, authenticated;
grant execute on function public.store_purchase, public.store_refund, public.grant_cores to service_role;
